Vendor latest

diff --git a/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons b/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
--- a/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
+++ b/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-export KUBECONFIG=/etc/kubernetes/config/addons-kubeconfig.yaml
-# kubectl 1.8.4
-KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:8cabd75bacbcdad7ac5d85efc3ca90c2fabf023b
+export KUBECONFIG=/etc/kubernetes/config/addons-kubeconfig.yml
+# kubectl 1.12.2
+KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:f5cae44c480bd797dc770dd5f62d40b74063c0d7
 
 /usr/bin/docker pull $KUBECTL
 
@@ -27,6 +27,39 @@ do
         sleep 5s
     done
 done
+
+# wait for etcd dns (return code 35 is bad certificate which is good enough here)
+while
+    curl "https://{{ .Cluster.Etcd.Domain }}:{{ .EtcdPort }}" -k 2>/dev/null >/dev/null
+    RET_CODE=$?
+    [ "$RET_CODE" -ne "35" ]
+do
+    echo "Waiting for etcd to be ready . . "
+    sleep 3s
+done
+
+# check for other master and remove it
+THIS_MACHINE=$(cat /etc/hostname)
+for master in $(/usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /etc/kubernetes:/etc/kubernetes $KUBECTL get nodes --no-headers=true --selector role=master | awk '{print $1}')
+do
+    if [ "$master" != "$THIS_MACHINE" ]; then
+        /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /etc/kubernetes:/etc/kubernetes $KUBECTL delete node $master
+    fi
+done
+
+# install kube-proxy
+PROXY_MANIFESTS="kube-proxy-sa.yaml kube-proxy-ds.yaml"
+for manifest in $PROXY_MANIFESTS
+do
+    while
+        /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv -v /etc/kubernetes:/etc/kubernetes $KUBECTL apply -f /srv/$manifest
+        [ "$?" -ne "0" ]
+    do
+        echo "failed to apply /srv/$manifest, retrying in 5 sec"
+        sleep 5s
+    done
+done
+echo "kube-proxy successfully installed"
 
 {{ if not .DisableCalico -}}
 
@@ -85,8 +118,6 @@ MANIFESTS=""
 {{ range .ExtraManifests -}}
 MANIFESTS="${MANIFESTS} {{ . }}"
 {{ end -}}
-MANIFESTS="${MANIFESTS} kube-proxy-sa.yaml"
-MANIFESTS="${MANIFESTS} kube-proxy-ds.yaml"
 MANIFESTS="${MANIFESTS} coredns.yaml"
 {{ if not .DisableIngressController -}}
 MANIFESTS="${MANIFESTS} default-backend-dep.yaml"
