Veeeendor

diff --git a/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons b/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
--- a/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
+++ b/vendor/github.com/giantswarm/k8scloudconfig/v_4_0_0/files/conf/k8s-addons
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-export KUBECONFIG=/etc/kubernetes/config/addons-kubeconfig.yaml
+export KUBECONFIG=/etc/kubernetes/kubeconfig/addons.yaml
 # kubectl 1.12.2
 KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:f5cae44c480bd797dc770dd5f62d40b74063c0d7
 
@@ -47,6 +47,16 @@ do
     sleep 3s
 done
 
+# create kube-proxy configmap
+while
+    /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv $KUBECTL create configmap kube-proxy --from-file=kube-proxy.yaml=/srv/kube-proxy-config.yaml -o yaml --dry-run \
+    | /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} -i --log-driver=none -a stdin -a stdout -a stderr --net=host --rm $KUBECTL apply -n kube-system -f -
+    [ "$?" -ne "0" ]
+do
+    echo "failed to configure kube-proxy from /srv/kube-proxy-confg.yaml, retrying in 5 sec"
+    sleep 5s
+done
+
 # install kube-proxy
 PROXY_MANIFESTS="kube-proxy-sa.yaml kube-proxy-ds.yaml"
 for manifest in $PROXY_MANIFESTS
@@ -60,6 +70,9 @@ do
     done
 done
 echo "kube-proxy successfully installed"
+
+# restart ds to apply config from configmap
+/usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv $KUBECTL delete pods -l k8s-app=kube-proxy -n kube-system
 
 {{ if not .DisableCalico -}}
 
